In [1]:
import pandas as pd
import numpy as np
from sklearn.impute import KNNImputer
import matplotlib.pyplot as plt
import seaborn as sns

import statsmodels.api as sm
import statsmodels.formula.api as smf
from statsmodels.stats.outliers_influence import variance_inflation_factor
from statsmodels.stats.stattools import durbin_watson

In [2]:
df = pd.read_csv("/content/water-quality-FINAL-cleaned.csv")

In [3]:
#MLR analysis
import statsmodels.api as sm
import statsmodels.formula.api as smf
from statsmodels.stats.outliers_influence import variance_inflation_factor
from statsmodels.stats.stattools import durbin_watson

In [4]:
target = 'Temperature'
predictors = [
    'pH', 'DO', 'Conductivity',
    'Total_N', 'Orthophosphate']


In [9]:
df = df.dropna()
df["WQI"] = (
    df['pH'] * .17 +
    df['DO'] * .26 +
    df['Conductivity'] * .11 +
    df['Temperature'] * .15 +
    df['Total_N'] * .15 +
    df['Orthophosphate'] * .15
)

In [22]:
from sklearn import svm
X = df[['pH', 'DO', 'Conductivity', 'Temperature', 'Total_N', 'Orthophosphate']]
df['WQI_bins'] = pd.cut(df['WQI'], bins = [0, .50, .70, 1.00], labels = ['Poor', 'Fair', 'Good'])
y = df['WQI_bins']
clf = svm.SVC()
clf.fit(X, y)

SVC()

In [23]:
clf.predict([[7.5, 8.0, 200, 15, 1.2, 0.1]])

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(


array(['Poor'], dtype=object)

In [24]:
# Help used: https://scikit-learn.org/stable/modules/svm.html

from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
from sklearn import svm
X_train , X_test , y_train, y_test = train_test_split(X, y, random_state=0)

clf = svm.SVC()
clf.fit(X_train, y_train)

clf.score(X_test, y_test)

0.9936293798013865

In [25]:
y.value_counts()

WQI_bins
Poor    51953
Fair     8053
Good     4035
Name: count, dtype: int64

In [26]:
# Help used: https://scikit-learn.org/stable/modules/generated/sklearn.metrics.confusion_matrix.html
# Help used: https://scikit-learn.org/stable/modules/generated/sklearn.metrics.classification_report.html
# Help used: https://scikit-learn.org/stable/modules/generated/sklearn.metrics.accuracy_score.html

from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

y_pred = clf.predict(X_test)

print(accuracy_score(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

0.9936293798013865
[[ 1988    10    29]
 [   19  1039     0]
 [   44     0 12882]]
              precision    recall  f1-score   support

        Fair       0.97      0.98      0.97      2027
        Good       0.99      0.98      0.99      1058
        Poor       1.00      1.00      1.00     12926

    accuracy                           0.99     16011
   macro avg       0.99      0.99      0.99     16011
weighted avg       0.99      0.99      0.99     16011



In [36]:
# Help used: https://scikit-learn.org/stable/modules/generated/sklearn.svm.SVR.html

from sklearn.svm import SVR
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_absolute_error, mean_squared_error

y2 = df['WQI']

X_train , X_test , y_train, y_test = train_test_split(X, y2, random_state=0)

regr = make_pipeline(StandardScaler(), SVR(C=1.0, epsilon=0.2))
regr.fit(X_train, y_train)

y_pred = regr.predict(X_test)

mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)

print("MAE: ", mae)
print("MSE: ", mse)

MAE:  0.0697458551828815
MSE:  0.00685458694320735
